:lang: en
:encoding: iso-8859-1

== BIBLIOGRAPHY ==
- *Valcu, M., James. D, Kempenaers, B.* rangeMapper: A platform for the study of macroecology of life history traits, Global Ecology and Biogeography, in press (2011)


<<results=ascii, echo=false>>=
s1 = version$version.string
s2 = paste("rangeMapper", packageDescription("rangeMapper")$Version)
s3 = paste("website generated using ascii", packageDescription("ascii")$Version)
ascii(rbind(s1, s2, s3))
@