:lang: en
:encoding: iso-8859-1
\Sexpr{options(prompt=" ", continue=" ")}
\SweaveOpts{prefix.string=figs/01}

== Map gallery ==
WARNING: Under construction

<<results=ascii, echo=false>>=
s1 = version$version.string
s2 = paste("rangeMapper", packageDescription("rangeMapper")$Version)
s3 = paste("website generated using ascii", packageDescription("ascii")$Version)
ascii(rbind(s1, s2, s3))
@