:lang: en
:encoding: iso-8859-1
\Sexpr{options(prompt=" ", continue=" ")}
\SweaveOpts{prefix.string=figs/01}

== Map gallery ==
WARNING: Under construction

<<results=ascii, echo=false>>=
s = paste("_Website built with ", version$version.string, 
		" and the package ", dQuote(packageDescription("ascii")$Package), " version ", packageDescription("ascii")$Version, "_", sep = "")
 
ascii(s, style = 'm', grid = 'none',width = 0,frame = "none")
@
