:lang: en
:encoding: iso-8859-1

== Graphical user interface ==

To get the latest version of the graphical user interface manual
type:
<<results=hide>>=
require(rangeMapper)
# vignette("rangeMapper")
@ 

<<results=ascii, echo=false>>=
s1 = version$version.string
s2 = paste("rangeMapper", packageDescription("rangeMapper")$Version)
s3 = paste("website generated using ascii", packageDescription("ascii")$Version)
ascii(rbind(s1, s2, s3))
@
